// <auto-generated />
namespace Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CriarTabelaPessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarTabelaPessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201911172129128_CriarTabelaPessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
